# **NUMPY**

##### **Numpy is a Fundamental Package for scientific computing in Python.** *It is a Python Library that provides a Multi Dimensional Array Object and various derived objects such as Masked Arrays or Matrices and an assortment of routines for fast operations on Arrays including Mathematical, Logical, Shape Manipulation, Sorting, Selecting, I/O, Discrete Fourier Transform, Basic Linear Algebra, Statistical Operations, Random Simulations,etc.

##### At the core of the Numpy Package is the n dimensional Array object.



## Why Numpy ?

### 2008-2009, Data Science ----> Matlab, R language

## Data Types in Python ---> **List, Dictionary --> Slow**

### *Syntax --> Python --> Easy*
### We needed speed and less memory to work with the huge amount of data.

### *Numpy ---> C Language ---> Wrapped ---> Python Language*
### *Numpy ---> Syntax ---> Easy for Beginners --> Performing Scientific Calculations----> Creating Multi Dimensional Arrays---> Speed is faster than applying Operations ---> Less Memory*

### Libraries like **Scikit Learn, Tensorflow and PyTorch** require input data in Numpy Arrays or Tensors.

## **Numpy Arrays** Vs **Python Sequences** 

#### Numpy Arrays have a fixed size at creation, unlike Python Lists which grow dynamistically. Chaning the size 0f an n dimentional array will create a new array and delete the original.

#### The elements in a Numpy Array are required to be of the same data type and thus will be of the same size in memory.

#### Numpy Arrays facilitate advanced Mathematical and other types of operations on large number of data. Typically, such operations are executed more efficiently with less code than is possile using python's built in sequences.

------

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
numpy_array = np.array([1, 2, 3])

In [4]:
numpy_array

array([1, 2, 3])

In [5]:
type(numpy_array)

numpy.ndarray

In [8]:
TwoD_array = np.array([[1, 2, 11,  12, 3], [4, 5, 7, 2, 6]])

In [9]:
TwoD_array

array([[ 1,  2, 11, 12,  3],
       [ 4,  5,  7,  2,  6]])

In [10]:
ThreeD_array = np.array([[[1, 2, 11,  12, 3], [4, 5, 7, 2, 6]], [[1, 2, 11,  12, 3], [4, 5, 7, 2, 6]]])

In [11]:
ThreeD_array

array([[[ 1,  2, 11, 12,  3],
        [ 4,  5,  7,  2,  6]],

       [[ 1,  2, 11, 12,  3],
        [ 4,  5,  7,  2,  6]]])

In [12]:
threeD_array = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [13]:
threeD_array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
threeD_array.shape

(2, 2, 2)

In [15]:
ThreeD_array.shape

(2, 2, 5)

-----------

In [ ]:
## np.array() - create an array from a list, tuple or any other sequence type (Multi-dimensional arrays can be created by nesting sequences)

In [ ]:
## D type parameter - Which can help us out deciding about the size of the data we are going to store inside our array.

In [16]:
np.array([1, 2, 3, 4, 5], dtype=np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [17]:
np.array([1, 2, 3, 4, 5], dtype="int64")

array([1, 2, 3, 4, 5])

In [ ]:
## np.float64 - 64 bit floating point number (or 8 bytes)
## np.float32 - 32 bit floating point number (or 4 bytes)
## np.int64 - 64 bit integer (or 8 bytes)
## np.int32 - 32 bit integer (or 4 bytes)

In [18]:
np.array([1, 2, 3], dtype=bool)

array([ True,  True,  True])

In [19]:
np.array([1, 2, 3], dtype=bool).dtype

dtype('bool')

-------

## **arange() function**

In [20]:
empty_list = []
for i in range(10):
    empty_list.append(i)
print(empty_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
## arange()- It helps us out with providing the values over a certain range and it also has a step parameter which can help us out with providing the values at a certain step size.

In [22]:
np.arange(1,17)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [26]:
np.arange(5,2,-1)

array([5, 4, 3])

In [24]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [27]:
np.arange(1,17)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

---------

## **reshape()**

In [28]:
arange_data=np.arange(1,17)

In [29]:
arange_data.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
## np.reshape() --> It helps us out with reshaping the data into a certain shape. It takes in the number of rows and columns as parameters and it reshapes the data accordingly.

In [30]:
np.arange(2,17,2).reshape(4,2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

----------

## **ones()**

In [31]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
## ones()- initialises the weight of a neural network with 1. It takes in the shape of the array as a parameter and it creates an array of that shape with all the values as 1.

-------

## **Zeros()** - 
##### initialises the weight of a neural network with 0. It takes in the shape of the array as a parameter and it creates an array of that shape with all the values as 0.

In [33]:
np.zeros((4,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

---

## **random()** - 
#### generates random numbers between 0 and 1. It takes in the shape of the array as a parameter and it creates an array of that shape with random values between 0 and 1.

In [35]:
np.random.random((3,4))

array([[0.62344211, 0.11516828, 0.34717707, 0.45721075],
       [0.20828241, 0.3935345 , 0.66449041, 0.86973222],
       [0.91107145, 0.28520416, 0.27014953, 0.63733625]])

----------

## **identity()** - 
#### *It helps us out with creating an identity matrix of a certain size. An identity matrix is a square matrix with 1's on the diagonal and 0's everywhere else.*

In [36]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

---------------

## **linspace()** 
#### *It makes sure that every value in the array is evenly spaced between a start and end value.*

In [37]:
np.linspace(-10, 10, 10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

---

# **Attributes**

 #### **ndim** - *It helps us out with finding the number of dimensions of an array.*

In [38]:
arr=np.array([1, 2, 3, 4, 5])

In [39]:
arr

array([1, 2, 3, 4, 5])

In [40]:
arr.ndim

1

In [41]:
array=np.array([[[1, 2], [4, 5]], [[1, 2], [4, 5]], [[1, 2], [4, 5]]])

In [42]:
array.ndim

3

In [43]:
np.array([1, 2, 3]).ndim

1

-----

## **shape()** - 
#### *It helps us out with finding the shape of an array.*

In [45]:
array.shape

(3, 2, 2)

------

## **size** - 
#### *It helps us out with finding the total number of elements in an array.*

In [46]:
np.array([1, 2, 3, 4, 5], dtype=np.float32).size

5

In [47]:
array_elements=np.arange(5,79,3)

In [48]:
array_elements.size

25

--------

In [ ]:
## itemsize() - It helps us out with finding the size of each element in the array in bytes.

In [49]:
np.array([1, 2, 3, 4, 5], dtype=np.float32).itemsize

4

-----

## **dtype** - 
#### *It helps us out with finding the data type of each element in the array.*

In [50]:
np.array([1, 2, 3], dtype="int32").dtype

dtype('int32')

------------

## **astype()** -->
#### *astype() will be helping us out with figuring out the data type of the column in the dataset in pandas and it will be used in numpy as well to convert the data type of the array to a certain data type. It takes in the data type as a parameter and it converts the data type of the array accordingly.*

In [6]:
array=np.arange(1,10).reshape(3,3)

In [7]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
array.astype(np.float64)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [9]:
type(array)

numpy.ndarray

In [10]:
array.dtype

dtype('int64')

In [11]:
array=array.astype(np.float64)

In [12]:
array.dtype

dtype('float64')

----------

## Mathematical Operations in Numpy

## **Scalar Operations** ---> *A scalar value operation will be done with the array or a numerical value (eg. 1,4)*

In [21]:
array = np.random.random((3,4))*100

In [22]:
array=np.round(array)

In [23]:
array=array.astype(np.int32)

In [24]:
array

array([[37, 78, 71, 16],
       [56, 66, 22, 99],
       [39, 38, 10, 79]], dtype=int32)

In [25]:
## Scalar Operations with our Matric and Array

In [26]:
array+2

array([[ 39,  80,  73,  18],
       [ 58,  68,  24, 101],
       [ 41,  40,  12,  81]], dtype=int32)

In [27]:
a=5
b=6
result=a+b
result

11

In [28]:
array - 5

array([[32, 73, 66, 11],
       [51, 61, 17, 94],
       [34, 33,  5, 74]], dtype=int32)

In [29]:
array*2

array([[ 74, 156, 142,  32],
       [112, 132,  44, 198],
       [ 78,  76,  20, 158]], dtype=int32)

--------------

#### *We can apply scalar operations with the array in terms of arithmetic operations.*

In [30]:
a=5
b=6
a>b

False

In [31]:
array>60

array([[False,  True,  True, False],
       [False,  True, False,  True],
       [False, False, False,  True]])

---

### *Vectorised Operations with our Matric and Array*

In [34]:
arr_1=np.arange(1,17).reshape(4,4)

In [33]:
arr_2=np.arange(17,33,).reshape(4,4)

In [35]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [36]:
arr_2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

----

In [37]:
arr_1 + arr_2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [38]:
arr_1 * arr_2

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

--------

#### **Important Functions in Numpy for Machine Learning and Data Science**

In [ ]:
## max() - It helps us out with finding the maximum value in the array.

## Syntax: np.max(array)

In [39]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [40]:
max_value=np.max(arr_1)

In [41]:
max_value

np.int64(16)

In [3]:
array_data=np.round(np.random.random((4,4))*100).astype(np.int32)

In [4]:
array_data

array([[91, 61, 48, 48],
       [88, 40, 99, 13],
       [20, 39, 29, 33],
       [57, 66, 41, 24]], dtype=int32)

--------

## **axis** ---> 
#### *It provides us with the idea about any operational value inside a speicifc row or column or we can get a specific value row wise or column wise. It is used in many functions like sum, mean, max, min etc.*

#### axis = 0 --> Column wise operation
#### axis = 1 --> Row wise operation

In [ ]:
np.max(array_data,axis=0)  ## column wise maximum

array([91, 66, 99, 48], dtype=int32)

In [ ]:
np.max(array_data, axis=1)  ## row wise maximum

array([91, 99, 39, 66], dtype=int32)

--------

## **min()** 
#### *It will be used for calculating minimum value from the matrix or array.*
### Syntax: **np.min(array)**

In [7]:
array_data

array([[91, 61, 48, 48],
       [88, 40, 99, 13],
       [20, 39, 29, 33],
       [57, 66, 41, 24]], dtype=int32)

In [8]:
np.min(array_data)

np.int32(13)

In [9]:
np.min(array_data, axis=0)  ## column wise minimum

array([20, 39, 29, 13], dtype=int32)

In [10]:
np.min(array_data, axis=1)  ## row wise minimum

array([48, 13, 20, 24], dtype=int32)

----

## **sum()** 
#### *It helps us out with finding the sum of all the elements in the matrix or array.*
### Syntax: **np.sum(array)**

In [11]:
np.sum(array_data)

np.int64(797)

In [12]:
np.sum(array_data, axis=0)  ## column wise sum

array([256, 206, 217, 118])

In [13]:
np.sum(array_data, axis=1)  ## row wise sum

array([248, 240, 121, 188])

-------

## **product()** - 
#### *It helps us out with finding the product of all the elements in the array. It also has an axis parameter which can help us out with finding the product along a certain axis.*
### Syntax: **np.prod(array, axis=None)**

In [14]:
array_data

array([[91, 61, 48, 48],
       [88, 40, 99, 13],
       [20, 39, 29, 33],
       [57, 66, 41, 24]], dtype=int32)

In [15]:
np.prod(array_data)  ## product of all the elements in the array

np.int64(-8466471735608213504)

In [17]:
np.prod(array_data, axis=0)  ## product along columns


array([9129120, 6280560, 5650128,  494208])

In [18]:
np.prod(array_data, axis=1)  ## product along rows

array([12789504,  4530240,   746460,  3701808])

--------

## **Statistical Functions in Numpy**

----

## **mean()** - 
#### *It helps us out with finding the mean of the array. It also has an axis parameter which can help us out with finding the mean along a certain axis.*
### Syntax: **np.mean(array, axis=None)**

In [19]:
array_data

array([[91, 61, 48, 48],
       [88, 40, 99, 13],
       [20, 39, 29, 33],
       [57, 66, 41, 24]], dtype=int32)

In [20]:
np.mean(array_data)  ## mean of all the elements in the array

np.float64(49.8125)

In [22]:
np.mean(array_data, axis=0)  ## mean along columns

array([64.  , 51.5 , 54.25, 29.5 ])

In [23]:
np.mean(array_data, axis=1)  ## mean along rows

array([62.  , 60.  , 30.25, 47.  ])

-------

## **std()** - 
#### *It helps us out with finding the standard deviation of the array. It can be used to find the standard deviation along a certain axis as well.*
#### syntax: **np.std(array)**  ## standard deviation 

In [24]:
np.std(array_data)  ## standard deviation of all the elements in the array

np.float64(24.92042021616008)

-----

In [ ]:
## axis=0 --> column wise std
## axis=1 --> row wise std

----

## **median()** -
#### *It helps us out with finding the median value in the array. The median is the middle value in a sorted list of numbers. If the list has an even number of elements, the median is the average of the two middle values.*

#### Syntax: **np.median(array)**

In [25]:
np.median(array_data)  ## median of all the elements in the array

np.float64(44.5)

In [26]:
np.median(array_data, axis=0)  ## median of each column

array([72.5, 50.5, 44.5, 28.5])

In [27]:
np.median(array_data, axis=1)  ## median of each row

array([54.5, 64. , 31. , 49. ])

------

## **var()**- 
#### *It helps us out with finding the variance of the array. It takes in the array as a parameter and it returns the variance of the array.*
#### Syntax: **np.var(array, axis=None)**

In [28]:
np.var(array_data)  ## variance of all the elements in the array

np.float64(621.02734375)

------

# Trigonometric Function

## **sin() / tan() / cos()** - 
#### *It helps us out with finding the sine of each element in the array. It takes in the array as a parameter and it returns an array with the sine of each element.*
#### Syntax: **np.sin(array)**

In [29]:
np.sin(0)

np.float64(0.0)

In [30]:
np.tan(0)

np.float64(0.0)

In [31]:
np.tan(np.radians(45))

np.float64(0.9999999999999999)

In [32]:
np.tan(45)

np.float64(1.6197751905438615)

In [33]:
np.cos(0)

np.float64(1.0)

---

## **Dot Product of Matrices**

#### syntax= **np.dot(matrix1,matrix2)**

In [34]:
matrix_1=np.round(np.random.random((3,4))*100).astype(np.int32)

In [35]:
matrix_1

array([[45, 83, 18, 79],
       [ 5, 28, 17,  2],
       [85, 36, 65,  9]], dtype=int32)

In [36]:
matrix_2=np.round(np.random.random((4,3))*100).astype(np.int32)

In [37]:
matrix_2

array([[66, 37, 97],
       [69, 28, 28],
       [77,  6, 73],
       [33,  3, 70]], dtype=int32)

In [38]:
np.dot(matrix_1, matrix_2)  ## matrix multiplication

array([[12690,  4334, 13533],
       [ 3637,  1077,  2650],
       [13396,  4570, 14628]], dtype=int32)

-----

## **log()** - 
#### *To calculate the log of all values of our Matrix*


In [39]:
matrix_1

array([[45, 83, 18, 79],
       [ 5, 28, 17,  2],
       [85, 36, 65,  9]], dtype=int32)

In [40]:
np.log(matrix_1)

array([[3.80666249, 4.41884061, 2.89037176, 4.36944785],
       [1.60943791, 3.33220451, 2.83321334, 0.69314718],
       [4.44265126, 3.58351894, 4.17438727, 2.19722458]])

------

## exp() - for exponential

In [41]:
np.exp(array_data)  ## exponential of all the elements in the array

array([[3.31740010e+39, 3.10429794e+26, 7.01673591e+20, 7.01673591e+20],
       [1.65163625e+38, 2.35385267e+17, 9.88903032e+42, 4.42413392e+05],
       [4.85165195e+08, 8.65934004e+16, 3.93133430e+12, 2.14643580e+14],
       [5.68572000e+24, 4.60718663e+28, 6.39843494e+17, 2.64891221e+10]])

---------

In [ ]:
## round() - It helps us out with rounding the values in the array to a certain number of decimal places. By default it rounds to the nearest integer.

In [42]:
np.round(array_data)

array([[91, 61, 48, 48],
       [88, 40, 99, 13],
       [20, 39, 29, 33],
       [57, 66, 41, 24]], dtype=int32)

---------

In [ ]:
## round()---> 1.6 rounds to 2  1.3 rounds to 1
## ceil()---> 1.6 rounds to 2  1.3 rounds to 2
## floor()---> 1.6 rounds to 1  1.3 rounds to 1

-----

In [ ]:
## ceil() - It helps us out with rounding the values in the array to the nearest next integer towards positive infinity.

In [43]:
np.ceil(array_data)

array([[91, 61, 48, 48],
       [88, 40, 99, 13],
       [20, 39, 29, 33],
       [57, 66, 41, 24]], dtype=int32)

-----

In [ ]:
## floor() - It helps us out with rounding the values in the array to the nearest previous integer towards negative infinity.

In [44]:
np.floor(array_data)

array([[91, 61, 48, 48],
       [88, 40, 99, 13],
       [20, 39, 29, 33],
       [57, 66, 41, 24]], dtype=int32)

-------

## **transpose()** - 
#### *It helps us out with transposing the array. It takes in the array as a parameter and it returns the transposed array.*

#### syntax: **np.transpose(array)**

#### (i,j)--->(j,i)

In [46]:
array = np.arange(1,17).reshape(4,4)

In [47]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [48]:
array.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [49]:
np.transpose(array)

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

------------

In [50]:
## **ravel()** - *It helps us out with flattening the array into a 1D array.*

#### syntax: **np.ravel(array)**


In [52]:
array.ndim

2

In [51]:
np.ravel(array)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

-----------

## Indexing and Slicing in Numpy Arrays

----

## **Indexing** --> **lists[,size-1]** 
#### *To have access to a particular element in the array we can use indexing. We can also use slicing to access a range of elements in the array. We can also use boolean indexing to access elements based on a condition.*

In [53]:
array=np.round(np.random.random((5,5))*100).astype(np.int32)

In [54]:
array

array([[88, 80, 93, 26, 87],
       [50, 11, 38, 21, 56],
       [35, 13, 72, 81, 18],
       [82, 24, 37, 62, 46],
       [33, 26, 22, 98, 74]], dtype=int32)

In [55]:
array_one=np.arange(1,10)

In [57]:
array_one[6]

np.int64(7)

In [58]:
array_one[7]

np.int64(8)

In [59]:
array

array([[88, 80, 93, 26, 87],
       [50, 11, 38, 21, 56],
       [35, 13, 72, 81, 18],
       [82, 24, 37, 62, 46],
       [33, 26, 22, 98, 74]], dtype=int32)

In [61]:
array[2,4]

np.int32(18)

In [62]:
array[4,4]

np.int32(74)

In [63]:
# 3d array
array_3d = np.array([[[1, 2], [4, 5]], [[1, 2], [4, 5]], [[1, 2], [4, 5]]])

In [64]:
array_3d

array([[[1, 2],
        [4, 5]],

       [[1, 2],
        [4, 5]],

       [[1, 2],
        [4, 5]]])

In [66]:
array_3d[1,0,1]

np.int64(2)

-------

## Slicing

In [ ]:
## Slicing ---> It helps us out with slicing the array into a certain shape. It takes in the start index, end index and step size as parameters and it slices the array accordingly.

## 2D Array ---> [row_start:row_end:row_step, column_start:column_end:column_step]

In [69]:
array

array([[88, 80, 93, 26, 87],
       [50, 11, 38, 21, 56],
       [35, 13, 72, 81, 18],
       [82, 24, 37, 62, 46],
       [33, 26, 22, 98, 74]], dtype=int32)

In [67]:
array[:,2]

array([93, 38, 72, 37, 22], dtype=int32)

In [68]:
array[0,:]

array([88, 80, 93, 26, 87], dtype=int32)

In [70]:
array[2:4,3:5]

array([[81, 18],
       [62, 46]], dtype=int32)

In [71]:
array[2:,1:4]

array([[13, 72, 81],
       [24, 37, 62],
       [26, 22, 98]], dtype=int32)

-------

In [ ]:
## Iterating over the array

In [72]:
array=np.arange(1,10)

In [73]:
for i in array:
    print(i)

1
2
3
4
5
6
7
8
9


In [74]:
array=np.arange(1,17).reshape(4,4)

In [75]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [76]:
for i in array:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [77]:
for i in array_3d:
    print(i)

[[1 2]
 [4 5]]
[[1 2]
 [4 5]]
[[1 2]
 [4 5]]


------

In [ ]:
## nditer() - It helps us out with iterating over the array in a more efficient way. It returns an iterator object which can be used to iterate over the array.
## np.idter()

In [78]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [81]:
for i in np.nditer(array):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [82]:
for i in np.nditer(array_3d):
    print(i)

1
2
4
5
1
2
4
5
1
2
4
5


In [ ]:
## 1D Array --> Vallue by value on iteration
## 2D Array --> Row by row on iteration
## 3D Array --> Matrix by matrix on iteration

-------------

## **Stacking and Splitting in array**

In [ ]:
## Stacking --> Joining the arrays together
## Horizontal Stacking --> Joining the arrays horizontally (column wise)
## Vertical Stacking --> Joining the arrays vertically (row wise)

In [83]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [87]:
horizontal_array=np.hstack((array,array))

In [88]:
horizontal_array

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [13, 14, 15, 16, 13, 14, 15, 16]])

In [89]:
vertical_array=np.vstack((array,array))

In [90]:
vertical_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
## Horizontal split --> np.hsplit(array, number of parts you want your array to be splitted at)
## vertical split --> np.vsplit(array, number of parts you want your array to be splitted at)

In [91]:
np.hsplit(vertical_array, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [92]:
np.vsplit(vertical_array, 2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [97]:
np.vsplit(vertical_array, 2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

-----

-----