# Modules and Packages

In [1]:
def addition(num1, num2):
    return num1 + num2

In [2]:
addition(5, 10)

15

-------------

### I want to use this logic of the function in this file into the other files

In [3]:
import math

In [4]:
math.sqrt(16)

4.0

In [ ]:
### How complex the logic of a square root function is going to be 


----------

## Module

#### A module in python is simply a file containing python code (function, classes or variables) that can be imported and used in other programs

------------

###  Numpy 
#### -----> Numpy Module is going to help us out with applying scientific calculation on the array and we can store our data by consuming less space and we can apply the operations with our array a bit more faster as compared to those of the list

#### -----> We can do it in Numpy just because Numpy is having the collection of functions and attributes which can help us to work efficiently with the array



---------

### Pandas

#### ----> Pandas we can use when we are going to work with the dataset for cleaning, pre processing, EDA, analysis with plotting as well

In [5]:
import math
math.sqrt(16)

4.0

In [6]:
from math import sqrt
sqrt(16)

4.0

In [7]:
from math import *
print(pi)

3.141592653589793


In [ ]:
## A Module:

## 1. A module helps in code organisation
## 2. A module helps in code reusability
## 3. A module helps in code clean and maintainability

In [8]:
print(cos(90))

-0.4480736161291701


In [9]:
import numpy

In [10]:
list_items=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
numpy_array=numpy.array(list_items)
type(numpy_array)
print(numpy_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
type(numpy_array)

numpy.ndarray

In [12]:
pip install seaborn

  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached kiwisolver-1.5.0-cp313-cp313-win_amd64.whl.metadata (5.2 kB)
  Using cached pillow-12.2.0-cp313-cp313-win_amd64.whl.metadata (9.0 kB)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   -------------------------------------- - 7.9/8.2 MB 39.4 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 34.3 MB/s  0:00:00
Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 26.4 MB/s  0:00:00
Using cached kiwisolver-1.5.0-cp313-cp313-win_a


[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


##### I am trying to create my own library and in this library i want the functions and the attribute to be created on my own

In [ ]:
## __init__.py__ file is used to make a directory a package. It can be an empty file or it can contain code that needs to be executed when the package is imported.

## File helps us out in defining our packages and initialising there namesppaces.

In [ ]:
## __init__.py__ file can remain empty and its completely fine but this file has to be their when we will be creating our new packages into the package folder

In [13]:
from package.mathematics import *

In [14]:
division(10, 2)

5.0

In [15]:
division(10, 0)

ValueError: Denominator cannot be zero.

In [16]:
from package.subpackage.sum import *

In [17]:
addi(5, 10)

15